game-store-demo/Models/ErrorViewModel.cs
using System;

namespace game_store_demo.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

game-store-demo/Models/VideoGame.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace game_store_demo.Models
{
    public class VideoGame
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }
        [Required]
        public string Name { get; set; }
        [Required]
        public string Console { get; set; }
        [Required]
        [Range(1,int.MaxValue, ErrorMessage ="Quantity must be greater than 0")]
        public int Quantity { get; set; }
        [Required]
        [Range(1, int.MaxValue, ErrorMessage = "Price must be greater than 0")]
        public int Price { get; set; }
    }
}

game-store-demo/Controllers/HomeController.cs
using game_store_demo.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace game_store_demo.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

game-store-demo/Controllers/VideoGameController.cs
using game_store_demo.Data;
using game_store_demo.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace game_store_demo.Controllers
{
    public class VideoGameController : Controller
    {
        private readonly GameStoreDbContext _db;

        public VideoGameController(GameStoreDbContext db)
        {
            _db = db;
        }

        public IActionResult Index()
        {
            IEnumerable<VideoGame> objList = _db.VideoGame;            
            return View(objList);
        }

        //GET 
        public IActionResult Create()
        {           
            return View();
        }

        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(VideoGame obj)
        {

            _db.VideoGame.Add(obj);
            _db.SaveChanges();
            //we go back to index so we can go back to see all videogames
            return RedirectToAction("Index");
         
        }

        //GET EDIT
        public IActionResult Edit(int? id)
        {
            if(id == null || id == 0)
            {
                return NotFound();
            }
            var obj = _db.VideoGame.Find(id);
            if(obj == null)
            {
                return NotFound();
            }

            return View(obj);
        }

        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(VideoGame obj)
        {
            _db.VideoGame.Update(obj);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }

        //GET DELETE
        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var obj = _db.VideoGame.Find(id);
            if (obj == null)
            {
                return NotFound();
            }

            return View(obj);
        }

        //POST DELETE
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult DeletePost(int? id)
        {
            var obj = _db.VideoGame.Find(id);
            if (id == null)
            {
                return NotFound();
            }
            _db.VideoGame.Remove(obj);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

game-store-demo/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

game-store-demo/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - game_store_demo</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Game Store</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="VideoGame" asp-action="Index">Video Games</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - game_store_demo - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

game-store-demo/Views/VideoGame/Create.cshtml
@model game_store_demo.Models.VideoGame

<form method="post" asp-action="Create">
    <div class="border p-3">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group" row>
            <h2 class="text-info pl-3">Add Videogame</h2>
        </div>
    </div>
    <br />
    <div class="row">
        <div class="col-8">
            <div class="form-group row">
                <div class="col-4">
                    <label asp-for="Name"></label>
                </div>
                <div class="col-8">
                    <input asp-for="Name" class="form-control" />
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group row">
                <div class="col-4">
                    <label asp-for="Console"></label>
                </div>
                <div class="col-8">
                    <input asp-for="Console" class="form-control" />
                    <span asp-validation-for="Console" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group row">
                <div class="col-4">
                    <label asp-for="Quantity"></label>
                </div>
                <div class="col-8">
                    <input asp-for="Quantity" class="form-control" />
                    <span asp-validation-for="Quantity" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group row">
                <div class="col-4">
                    <label asp-for="Price"></label>
                </div>
                <div class="col-8">
                    <input asp-for="Price" class="form-control" />
                    <span asp-validation-for="Price" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group row">
                <div class="col-8 offset-4 row">
                    <div class="col">
                        <a asp-action="Index" class="btn btn-success w-100"><i class="fas fa-sign-out-alt"></i> Back</a>
                    </div>
                    <div class="col">
                        <input type="submit" class="btn btn-info w-100" value="Create" />
                    </div>
                </div>
            </div>
        </div>
        <div class="col-4">
            @* Keep this empty *@
        </div>
    </div>
</form>

<!--Client side validation-->
@section Scripts{ 
    @{ <partial name="_ValidationScriptsPartial" /> }
}

game-store-demo/Views/VideoGame/Delete.cshtml
@model game_store_demo.Models.VideoGame

<form method="post" asp-action="DeletePost">
    <input asp-for="Id" hidden />
    <div class="border p-3">
        <div class="form-group" row>
            <h2 class="text-info pl-3">Delete Videogame</h2>
        </div>
    </div>
    <br />
    <div class="row">
        <div class="col-8">
            <div class="form-group row">
                <div class="col-4">
                    <label asp-for="Name"></label>
                </div>
                <div class="col-8">
                    <input asp-for="Name" disabled class="form-control" />
                </div>
            </div>
            <div class="form-group row">
                <div class="col-4">
                    <label asp-for="Console"></label>
                </div>
                <div class="col-8">
                    <input asp-for="Console" disabled class="form-control" />
                </div>
            </div>
            <div class="form-group row">
                <div class="col-4">
                    <label asp-for="Quantity"></label>
                </div>
                <div class="col-8">
                    <input asp-for="Quantity" disabled class="form-control" />
                </div>
            </div>
            <div class="form-group row">
                <div class="col-4">
                    <label asp-for="Price"></label>
                </div>
                <div class="col-8">
                    <input asp-for="Price" disabled class="form-control" />
                </div>
            </div>
            <div class="form-group row">
                <div class="col-8 offset-4 row">
                    <div class="col">
                        <a asp-action="Index" class="btn btn-success w-100"><i class="fas fa-sign-out-alt"></i> Back</a>
                    </div>
                    <div class="col">
                        <input type="submit" class="btn btn-danger w-100" value="Delete" />
                    </div>
                </div>
            </div>
        </div>
        <div class="col-4">
            @* Keep this empty *@
        </div>
    </div>
</form>

<!--Client side validation-->
@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

game-store-demo/Views/VideoGame/Edit.cshtml
@model game_store_demo.Models.VideoGame

<form method="post">
    <input asp-for="Id" hidden />
    <div class="border p-3">
        <div class="form-group" row>
            <h2 class="text-info pl-3">Edit Videogame</h2>
        </div>
    </div>
    <br />
    <div class="row">
        <div class="col-8">
            <div class="form-group row">
                <div class="col-4">
                    <label asp-for="Name"></label>
                </div>
                <div class="col-8">
                    <input asp-for="Name" class="form-control" />
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group row">
                <div class="col-4">
                    <label asp-for="Console"></label>
                </div>
                <div class="col-8">
                    <input asp-for="Console" class="form-control" />
                    <span asp-validation-for="Console" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group row">
                <div class="col-4">
                    <label asp-for="Quantity"></label>
                </div>
                <div class="col-8">
                    <input asp-for="Quantity" class="form-control" />
                    <span asp-validation-for="Quantity" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group row">
                <div class="col-4">
                    <label asp-for="Price"></label>
                </div>
                <div class="col-8">
                    <input asp-for="Price" class="form-control" />
                    <span asp-validation-for="Price" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group row">
                <div class="col-8 offset-4 row">
                    <div class="col">
                        <a asp-action="Index" class="btn btn-success w-100"><i class="fas fa-sign-out-alt"></i> Back</a>
                    </div>
                    <div class="col">
                        <input type="submit" class="btn btn-info w-100" value="Update" />
                    </div>
                </div>
            </div>
        </div>
        <div class="col-4">
            @* Keep this empty *@
        </div>
    </div>
</form>

<!--Client side validation-->
@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

game-store-demo/Views/VideoGame/Index.cshtml
<!--Catch the object sent by the controller-->
@model IEnumerable<game_store_demo.Models.VideoGame>

<div class="container p-3">
    <div class="row pt-4">
        <div class="col-6">
            <h2 class="text-primary">Videogame List</h2>
        </div>
        <div class="col-6 text-right" >
            <a asp-controller="VideoGame" asp-action="Create" class="btn btn-primary">
                Insert New Videogame
            </a>
        </div>
    </div>

    <br /><br />

    @if (Model.Count() > 0)
    {
        <table class="table table-bordered table-striped" style="width:100%">
            <thead>
                <tr>
                    <th>
                        Videogame Name
                    </th>
                    <th>
                        Console
                    </th>
                    <th>
                        Quantity
                    </th>
                    <th>
                        Price
                    </th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var obj in Model)
                {
                <tr>
                    <td width="22%">@obj.Name</td>
                    <td width="22%">@obj.Console</td>
                    <td width="22%">@obj.Quantity</td>
                    <td width="22%">@obj.Price</td>
                    <td class="text-center">
                        <div class="w-60 btn-group" role="group">
                            <a asp-controller="VideoGame"asp-route-Id="@obj.Id" asp-action="Edit" class="btn btn-primary mx-2">
                                Edit
                            </a>
                            <a asp-controller="VideoGame" asp-route-Id="@obj.Id" asp-action="Delete" class="btn btn-danger mx-2">
                                Delete
                            </a>
                        </div>
                    </td>
                </tr>
                }



            </tbody>
        </table>
    }
    else { 
        <p>No Videogames exist</p>
    }

</div>